server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: practico-auth-service
  profiles:
    default: local
  sql:
    init:
      mode: never

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: auth
    default-schema: auth
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth
    show-sql: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

auth:
  jwt:
    key-id: ${AUTH_JWT_KEY_ID:practico-auth-k1}
    access-token-ttl-seconds: ${AUTH_JWT_ACCESS_TOKEN_TTL_SECONDS:3600}
