server:
  port: ${SERVER_PORT:8081}

spring:
  sql:
    init:
      mode: never

  datasource:
    url: jdbc:postgresql://localhost:5432/practico
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: auth
    default-schema: auth
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
