server:
  port: ${SERVER_PORT:8081}

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false

auth:
  jwt:
    key-id: ${AUTH_JWT_KEY_ID}
    access-token-ttl-seconds: ${AUTH_JWT_ACCESS_TOKEN_TTL_SECONDS:3600}
  providers:
    google:
      enabled: ${AUTH_PROVIDERS_GOOGLE_ENABLED:true}
      client-id: ${AUTH_PROVIDERS_GOOGLE_CLIENT_ID}
