telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN}

auth:
  jwt-validation:
    jwks-uri: ${AUTH_JWKS_URI:http://127.0.0.1:8081/.well-known/jwks.json}

openai:
  api-key: ${OPENAI_API_KEY:}
  model: ${OPENAI_MODEL:gpt-5-mini}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${auth.jwt-validation.jwks-uri}
  sql:
    init:
      mode: never

  datasource:
    url: jdbc:postgresql://localhost:5432/practico
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: core
    default-schema: core
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: core
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
